FROM node:16-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY . .
RUN node scripts/build.js


FROM node:16-alpine

WORKDIR /app

RUN npm install -g serve
COPY --from=build /app/build/ .

EXPOSE 3000
CMD ["serve", "-s"]
