FROM node:18-alpine

WORKDIR /app
ENV NODE_ENV production

COPY package*.json ./
RUN npm ci

COPY /config/ ./config
COPY /scripts/start-server-*.js ./scripts/
COPY /src-server/ ./src-server

EXPOSE 3000
CMD ["npm", "run", "start"]
